farmakami/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('apotek/', include('apotek.urls')),
    path('produk-apotek/', include('produk_apotek.urls')),
    path('balai-pengobatan/', include('balai_pengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/', include('transaksi_pembelian.urls')),
    path('profil/', include('profil.urls')),
    path('produk-dibeli/', include('list_produk_dibeli.urls')),
    path('pengantaran-farmasi/', include('pengantaran_farmasi.urls')),
    path('no-access/', views.no_access, name='no_access'),
]

login/urls.py
from django.urls import path, include
from . import views

app_name = "login"

urlpatterns = [
    path('', views.home_login, name="home_login"),
    path('form-login/', views.form_login, name='form_login'),
    path('form-login-submit/', views.form_login_submit, name='form_login_submit'),
    path('logout/', views.home_logout, name='home_logout'),

    path('register/', views.register, name='register'),
    path('form-register/<str:role>', views.form_register, name='form_register'),
    path('form-register-konsumen/', views.form_register_konsumen, name='form_register_konsumen'),
    path('form-register-admin/', views.form_register_admin, name='form_register_admin'),
    path('form-register-kurir/', views.form_register_kurir, name='form_register_kurir'),
    path('form-register-cs/', views.form_register_cs, name='form_register_cs'),
]

obat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.obat_read, name="obat_read"),
    path('create/', views.obat_create, name="obat_create"),
    path('create-submit/', views.obat_create_submit, name="obat_create_submit"),
    path('update/<str:id_obat>', views.obat_update, name="obat_update"),
    path('update-submit/', views.obat_update_submit, name="obat_update_submit"),
    path('delete/<str:id_obat>', views.obat_delete, name="obat_delete"),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.db import connection
from balai_pengobatan.views import count_next_id


def home_login(request):
    return render(request, 'home_login.html')


def form_login(request):
    return render(request, 'form_login.html', {
        'failed': request.GET.get('failed')
    })


def form_login_submit(request):
    try:
        email = request.POST['email']
        password = request.POST['password']
        do_login(request, email, password)
        return redirect("profil-home")
    except:
        return redirect(reverse("login:form_login") + "?failed=true")


def home_logout(request):
    request.session.flush()
    return redirect("login:home_login")


def register(request):
    return render(request, 'register.html')


def form_register(request, role):
    list_idapotek = []
    if role == "admin":
        role_pendaftaran = "ADMIN"
        with connection.cursor() as cursor:
            cursor.execute(
                'SELECT id_apotek FROM apotek')
            list_idapotek = [col[0] for col in cursor.fetchall()]
    elif role == "konsumen":
        role_pendaftaran = "KONSUMEN"
    elif role == "kurir":
        role_pendaftaran = "KURIR"
    else:
        role_pendaftaran = "CS"
    return render(request, 'form_register.html', {
        'role_pendaftaran': role_pendaftaran,
        'list_idapotek' : list_idapotek,
        'failed': request.GET.get('failed'),
        'success': request.GET.get('success')
    })


def form_register_konsumen(request):
    try:
        email = request.POST['email']
        password = request.POST['password']
        nama_lengkap = request.POST['nama_lengkap']
        no_telepon = request.POST['no_telepon']
        jenis_kelamin = request.POST['jenis_kelamin']
        tanggal_lahir = request.POST['tanggal_lahir']
        next_konsumen_id = "k" + str(count_next_id("konsumen", "id_konsumen", "k"))

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM pengguna WHERE email = %s", (email,))
            if len(cursor.fetchall()) > 0:
                return redirect(reverse("login:form_register", args=["konsumen"]) + "?failed=duplicate")

            cursor.execute("INSERT INTO pengguna VALUES (%s, %s, %s, %s)", (
                email, no_telepon, password, nama_lengkap
            ))

            cursor.execute("INSERT INTO konsumen VALUES (%s, %s, %s, %s)", (
                next_konsumen_id, email, jenis_kelamin, tanggal_lahir
            ))

            for key, status_alamat in request.POST.items():
                if key[:14] == 'status_alamat_':
                    nama_alamat = request.POST['nama_alamat_' + key[14:]]
                    cursor.execute("INSERT INTO alamat_konsumen VALUES (%s, %s, %s)", (
                        next_konsumen_id, nama_alamat, status_alamat
                    ))

            do_login(request, email, password)
            return redirect(reverse("login:form_register", args=["konsumen"]) + "?success=true")
    except:
        return redirect(reverse("login:form_register", args=["konsumen"]) + "?failed=true")


def form_register_admin(request):
    try:
        email = request.POST['email']
        password = request.POST['password']
        nama_lengkap = request.POST['nama_lengkap']
        no_telepon = request.POST['no_telepon']
        id_apotek = request.POST['id_apotek']

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM pengguna WHERE email = %s", (email,))
            if len(cursor.fetchall()) > 0:
                return redirect(reverse("login:form_register", args=["admin"]) + "?failed=duplicate")

            cursor.execute("INSERT INTO pengguna VALUES (%s, %s, %s, %s)", (
                email, no_telepon, password, nama_lengkap
            ))

            cursor.execute("INSERT INTO apoteker VALUES (%s)", (
                email,
            ))

            cursor.execute("INSERT INTO admin_apotek VALUES (%s, %s)", (
                email, id_apotek
            ))

            do_login(request, email, password)
            return redirect(reverse("login:form_register", args=["admin"]) + "?success=true")
    except:
        return redirect(reverse("login:form_register", args=["admin"]) + "?failed=true")


def form_register_kurir(request):
    try:
        email = request.POST['email']
        password = request.POST['password']
        nama_lengkap = request.POST['nama_lengkap']
        no_telepon = request.POST['no_telepon']
        nama_perusahaan = request.POST['id_nama_perusahaan']
        next_kurir_id = "kurir" + str(count_next_id("kurir", "id_kurir", "kurir"))

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM pengguna WHERE email = %s", (email,))
            if len(cursor.fetchall()) > 0:
                return redirect(reverse("login:form_register", args=["kurir"]) + "?failed=duplicate")

            cursor.execute("INSERT INTO pengguna VALUES (%s, %s, %s, %s)", (
                email, no_telepon, password, nama_lengkap
            ))

            cursor.execute("INSERT INTO kurir VALUES (%s, %s, %s)", (
                next_kurir_id, email, nama_perusahaan
            ))

            do_login(request, email, password)
            return redirect(reverse("login:form_register", args=["kurir"]) + "?success=true")
    except:
        return redirect(reverse("login:form_register", args=["kurir"]) + "?failed=true")


def form_register_cs(request):
    try:
        email = request.POST['email']
        password = request.POST['password']
        nama_lengkap = request.POST['nama_lengkap']
        no_telepon = request.POST['no_telepon']
        no_ktp = request.POST['id_no_ktp']
        no_sia = request.POST['id_no_sia']

        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM pengguna WHERE email = %s", (email,))
            if len(cursor.fetchall()) > 0:
                return redirect(reverse("login:form_register", args=["cs"]) + "?failed=duplicate")

            cursor.execute("INSERT INTO pengguna VALUES (%s, %s, %s, %s)", (
                email, no_telepon, password, nama_lengkap
            ))

            cursor.execute("INSERT INTO apoteker VALUES (%s)", (
                email,
            ))

            cursor.execute("INSERT INTO cs VALUES (%s, %s, %s)", (
                no_ktp, email, no_sia
            ))

            do_login(request, email, password)
            return redirect(reverse("login:form_register", args=["cs"]) + "?success=true")
    except:
        return redirect(reverse("login:form_register", args=["cs"]) + "?failed=true")


# Utility function
def do_login(request, email, password):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM pengguna WHERE email = %s", (email,))
        result = cursor.fetchall()
        if len(result) == 1:
            user = result[0]
            if user[2] == password:
                cursor.execute("SELECT * FROM konsumen WHERE email = %s", (email,))
                role = []
                if len(cursor.fetchall()) == 1:
                    role.append("konsumen")

                cursor.execute("SELECT * FROM apoteker WHERE email = %s", (email,))
                if len(cursor.fetchall()) == 1:
                    role.append("apoteker")

                cursor.execute("SELECT * FROM cs WHERE email = %s", (email,))
                if len(cursor.fetchall()) == 1:
                    role.append("cs")

                cursor.execute("SELECT * FROM admin_apotek WHERE email = %s", (email,))
                if len(cursor.fetchall()) == 1:
                    role.append("admin_apotek")

                cursor.execute("SELECT * FROM kurir WHERE email = %s", (email,))
                if len(cursor.fetchall()) == 1:
                    role.append("kurir")

                if len(role) > 0:
                    request.session['email'] = email
                    request.session['role'] = role
                    return
    
    raise Exception("failed login")

login/templates/form_login.html
{% extends 'home.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block navbar %}{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/animate.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex align-items-center justify-content-center" style="height:100vh">
            <div class="animate__animated animate__fadeInDown animate__slow">
                <d style="text-align:left"><h1>Login</h1></d>
                {% if failed %}
                    <div class="alert alert-danger" role="alert">
                        Wrong email/password
                    </div>
                {% endif %}
                <form method="POST" action="{% url 'login:form_login_submit' %}">
                    {% csrf_token %}
                    <div class="form-group" style="margin-top:1rem">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email"
                               style="max-width: 300px; display: inline;">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password"
                               style="max-width: 300px; display: inline;">
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
                <br>
                <br>
            </div>
        </div>
    </div>
{% endblock %}

login/templates/form_register.html
{% extends 'home.html' %}

{% load static %}

{% block title %}Register {{ role_pendaftaran | title }}{% endblock %}

{% block navbar %}{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/animate.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex align-items-center justify-content-center" style="min-height:100vh">
            <div class="animate__animated animate__fadeInDown animate__slow">
                <br>
                <d style="text-align:center"><h1>FORM PENDAFTARAN {{ role_pendaftaran }}</h1></d>
                {% if failed == 'duplicate' %}
                    <div class="alert alert-danger" role="alert">
                        Your email is already registered. Please login
                    </div>
                {% elif failed %}
                    <div class="alert alert-danger" role="alert">
                        Register failed. Please input a valid data
                    </div>
                {% elif success %}
                    <div class="alert alert-success" role="alert">
                        Register successful!<br/>
                        You will be redirected in <span id="reg-success-cnt">6...</span><br/>
                        <a href="{% url 'profil-home' %}">Click here</a> if you are not redirected automatically
                    </div>
                {% endif %}

                {% if role_pendaftaran == "KONSUMEN" %}
                    <form action="{% url 'login:form_register_konsumen' %}" method="POST">
                {% elif role_pendaftaran == "ADMIN" %}
                    <form action="{% url 'login:form_register_admin' %}" method="POST">
                {% elif role_pendaftaran == "KURIR" %}
                    <form action="{% url 'login:form_register_kurir' %}" method="POST">
                {% elif role_pendaftaran == "CS" %}
                    <form action="{% url 'login:form_register_cs' %}" method="POST">
                {% endif %}
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Email</label>
                    <input name="email" type="email" class="form-control" id="id_email" required="required">
                </div>
                <div class="form-group">
                    <label for="id_password">Password</label>
                    <input name="password" type="password" class="form-control" id="id_password">
                </div>
                <div class="form-group">
                    <label for="id_nama_lengkap">Nama Lengkap</label>
                    <input name="nama_lengkap" type="text" class="form-control" id="id_nama_lengkap">
                </div>
                <div class="form-group">
                    <label for="id_no_telepon">No Telepon</label>
                    <input name="no_telepon" type="text" class="form-control" id="id_no_telepon">
                </div>
                {% if role_pendaftaran == "KONSUMEN" %}
                    <div class="form-group">
                        <label for="id_jenis_kelamin">Jenis Kelamin</label>
                        <input name="jenis_kelamin" type="text" class="form-control" id="id_jenis_kelamin">
                    </div>
                    <div class="form-group">
                        <label for="id_tanggal_lahir">Tanggal Lahir</label>
                        <input name="tanggal_lahir" type="date" class="form-control" id="id_tanggal_lahir">
                    </div>
                    <div>
                        <h6>Alamat:</h6>
                        <div id="id_list_alamat">
                            <div id="id_container_alamat_1">
                                <button type="button" class="btn btn-danger" style="margin-right: 5px;"
                                        onclick="removeAlamat(1)" id="button_alamat_1">-
                                </button>
                                <input type="text" class="form-control" name="status_alamat_1" id="id_status_alamat_1"
                                       style="max-width: 200px; display: inline;" placeholder="Status Alamat">
                                <input type="text" class="form-control" name="nama_alamat_1" id="id_nama_alamat_1"
                                       style="max-width: 200px; display: inline;" placeholder="Nama Alamat">
                            </div>
                        </div>
                        <button type="button" class="btn btn-primary" style="margin-right: 5px; margin-top: 5px;"
                                onclick="addAlamat()">+
                        </button>
                    </div>
                {% elif role_pendaftaran == "KURIR" %}
                    <div class="form-group">
                        <label for="id_nama_perusahaan">Nama Perusahaan</label>
                        <input name="id_nama_perusahaan" type="text" class="form-control" id="id_nama_perusahaan">
                    </div>
                {% elif role_pendaftaran == "CS" %}
                    <div class="form-group">
                        <label for="id_no_ktp">No KTP</label>
                        <input name="id_no_ktp" type="text" class="form-control" id="id_no_ktp">
                    </div>
                    <div class="form-group">
                        <label for="id_no_sia">No SIA</label>
                        <input name="id_no_sia" type="text" class="form-control" id="id_no_sia">
                    </div>
                {% elif role_pendaftaran == "ADMIN" %}
                    <div class="form-group">
                        <label for="id_apotek">ID Apotek</label>
                        <select class="form-control" id="id_apotek" name="id_apotek">
                            {% for id in list_idapotek %}
                                <option>{{ id }}</option>
                            {% endfor %}
                        </select>
                    </div>
                {% endif %}
                <button type="submit" class="btn btn-primary" style='margin-top: 5px;'>Submit</button>
                </form>
                <br>
                <br>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {% if success %}
        <script>
            $( document ).ready(function() {
                let regSuccessCnt = 6;
                let autoRedirect = setInterval(function() {
                    --regSuccessCnt;
                    if (regSuccessCnt >= 0) {
                        document.getElementById("reg-success-cnt").innerText = regSuccessCnt + "...";
                    }
                    if (regSuccessCnt == 0) {
                        clearInterval(autoRedirect);
                        window.location.replace("{% url 'profil-home' %}");
                    }
                }, 1000)
            });
        </script>
    {% endif %}
    <script>
        var count_alamat = 1

        function addAlamat() {
            count_alamat++;

            const new_alamat_container = document.createElement("div")
            new_alamat_container.id = `id_container_alamat_${count_alamat}`

            new_alamat_container.innerHTML =
                `<button type="button" class="btn btn-danger" style="margin-right: 5px;" onclick="removeAlamat(${count_alamat})" id="button_alamat_${count_alamat}">-</button>
      <input type="text" class="form-control" name="status_alamat_${count_alamat}" id="id_status_alamat_${count_alamat}" style="max-width: 200px; display: inline;" placeholder="Status Alamat">
      <input type="text" class="form-control" name="nama_alamat_${count_alamat}" id="id_nama_alamat_${count_alamat}" style="max-width: 200px; display: inline;" placeholder="Nama Alamat">`

            const list_alamat = document.getElementById("id_list_alamat")
            list_alamat.appendChild(new_alamat_container)
        }

        function removeAlamat(number) {
            const list_alamat = document.getElementById("id_list_alamat")
            if (list_alamat.children.length > 1) {
                const alamat = document.getElementById(`id_container_alamat_${number}`)
                list_alamat.removeChild(alamat);
            }
        }

    </script>
{% endblock %}

login/templates/home_login.html
{% extends 'home.html' %}

{% load static %}

{% block title %}Home{% endblock %}

{% block navbar %}{% endblock %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/awesomebg.css' %}">
{% endblock %}

{% block content %}
    <canvas id="scene"></canvas>
    <input id="copy" type="hidden" value="FarmaKami ♥"/>
    <div id="info">
        <hr class="animate__animated animate__fadeIn animate__slow"/>
        <div class="animate__animated animate__fadeIn animate__slow animate__delay-1s">
            <h1>FarmaKami</h1>
        </div>
        <div class="animate__animated animate__fadeIn animate__slow animate__delay-2s">
            <a href="{% url 'login:form_login' %}">
                <button type="button" class="btn btn-primary" style="margin-right: 5px;">Login</button>
            </a>
            <a href="{% url 'login:register' %}">
                <button type="button" class="btn btn-success" style="margin-left: 5px;">Register</button>
            </a>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'login/awesomebg.js' %}"></script>
{% endblock %}

login/templates/register.html
{% extends 'home.html' %}

{% block title %}Register{% endblock %}

{% block navbar %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="d-flex align-items-center justify-content-center" style="height:100vh">
            <div>
                <d style="text-align:center"><h4>Pilih Role</h4></d>
                <d style="display: flex; justify-content: center;">
                    <a href="{% url 'login:form_register' role='admin' %}">
                        <button type="button" class="btn btn-success" style="margin-right: 5px;">Admin Apotek</button>
                    </a>
                    <a href="{% url 'login:form_register' role='konsumen' %}">
                        <button type="button" class="btn btn-success" style="margin-right: 5px;">Konsumen</button>
                    </a>
                    <a href="{% url 'login:form_register' role='kurir' %}">
                        <button type="button" class="btn btn-success" style="margin-right: 5px;">Kurir</button>
                    </a>
                    <a href="{% url 'login:form_register' role='cs' %}">
                        <button type="button" class="btn btn-success" style="margin-right: 5px;">CS</button>
                    </a>
                </d>
                <br>
                <br>
            </div>
        </div>
    </div>
{% endblock %}