farmakami/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('apotek/', include('apotek.urls')),
    path('produk-apotek/', include('produk_apotek.urls')),
    path('balai-pengobatan/', include('balai_pengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/', include('transaksi_pembelian.urls')),
    path('profil/', include('profil.urls')),
    path('produk-dibeli/', include('list_produk_dibeli.urls')),
    path('pengantaran-farmasi/', include('pengantaran_farmasi.urls')),
    path('no-access/', views.no_access, name='no_access'),
]

obat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.obat_read, name="obat_read"),
    path('create/', views.obat_create, name="obat_create"),
    path('create-submit/', views.obat_create_submit, name="obat_create_submit"),
    path('update/<str:id_obat>', views.obat_update, name="obat_update"),
    path('update-submit/', views.obat_update_submit, name="obat_update_submit"),
    path('delete/<str:id_obat>', views.obat_delete, name="obat_delete"),
]

produk_apotek/urls.py
from django.urls import path, include
from . import views

app_name = "produk_apotek"

urlpatterns = [
    path('', views.rud_produk_apotek, name="rud_produk_apotek"),
    path('update/<str:id_apotek>/<str:id_produk>', views.update_produk_apotek, name='update_produk_apotek'),
    path('delete/<str:id_apotek>/<str:id_produk>', views.delete_produk_apotek, name='delete_produk_apotek'),
    path('create/', views.create_produk_apotek, name='create_produk_apotek'),
]

produk_apotek/models.py
from django.db import models

# Create your models here.

produk_apotek/forms.py
from django import forms

class produk_apotek_form(forms.Form):

    def __init__(self,id_apotek_choices=None, id_produk_choices=None, *args, **kwargs, ):
        super(produk_apotek_form, self).__init__(*args, **kwargs)
        self.fields['id_apotek'].choices = id_apotek_choices
        self.fields['id_produk'].choices = id_produk_choices

    id_apotek = forms.ChoiceField(
        label = 'Id Apotek',
        choices=()
    )

    id_produk = forms.ChoiceField(
        label = 'Id Produk',
        choices=()
    )
    
    harga_jual = forms.CharField(
        label = 'Harga Jual'
    )

    satuan_penjualan = forms.CharField(
        label = 'Satuan Penjualan',
        max_length = 5
    )

    stok = forms.CharField(
        label = 'Stok'
    )

produk_apotek/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse  
from django.db import DataError, IntegrityError, connection   
from .forms import *  
from django.contrib import messages
from login.decorators import only_pengguna

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]      

@only_pengguna()
def rud_produk_apotek(request):
    with connection.cursor() as cursor:
        cursor.execute("select * from produk_apotek order by length(id_produk), id_produk")
        rows = dictfetchall(cursor)
    return render(request, 'produk_apotek.html', {'rows':rows})

@only_pengguna("admin_apotek")
def update_produk_apotek(request, id_apotek, id_produk):
    with connection.cursor() as cursor:
        if request.method == 'POST':
            forms = produk_apotek_form(generate_id_apotek_choices(), generate_id_produk_choices(), request.POST)
            if forms.is_valid():
                try:
                    cursor.execute(
                        """update produk_apotek set 
                        harga_jual = %s, 
                        stok = %s,
                        satuan_penjualan = %s,
                        id_produk = %s,
                        id_apotek = %s
                        where id_apotek = %s and id_produk = %s""", 
                        [
                        forms.cleaned_data['harga_jual'],
                        forms.cleaned_data['stok'],
                        forms.cleaned_data['satuan_penjualan'],
                        forms.cleaned_data['id_produk'],
                        forms.cleaned_data['id_apotek'],
                        id_apotek,
                        id_produk
                        ])
                    return redirect('produk_apotek:rud_produk_apotek') 
                except IntegrityError:
                    messages.info(request, "Error: Pasangan id apotek dan id produk tidak boleh sama dengan produk apotek yang lain")
                    return redirect('produk_apotek:update_produk_apotek', id_apotek=id_apotek, id_produk=id_produk)
                except DataError:
                    messages.info(request, "Error: Harga jual atau stok harus berupa angka")
                    return redirect('produk_apotek:update_produk_apotek', id_apotek=id_apotek, id_produk=id_produk)
        else:
            cursor.execute("select * from produk_apotek where id_apotek=%s and id_produk=%s", [id_apotek, id_produk])
            produk_apotek = dictfetchall(cursor)[0]
            forms = produk_apotek_form(generate_id_apotek_choices(), generate_id_produk_choices(),  
                initial = {
                    'id_apotek': produk_apotek['id_apotek'],
                    'id_produk': produk_apotek['id_produk'],
                    'harga_jual': produk_apotek['harga_jual'],
                    'satuan_penjualan': produk_apotek['satuan_penjualan'],
                    'stok': produk_apotek['stok']
                }
            )
            return render(request, 'update_produk_apotek.html', {'forms':forms})

@only_pengguna("admin_apotek")
def delete_produk_apotek(request, id_apotek, id_produk):
    with connection.cursor() as cursor:
        cursor.execute("delete from produk_apotek where id_apotek = %s and id_produk = %s", [id_apotek, id_produk])
        return redirect('produk_apotek:rud_produk_apotek')
    
@only_pengguna("admin_apotek")
def create_produk_apotek(request):
    with connection.cursor() as cursor:
        if request.method == 'POST':
            forms = produk_apotek_form(generate_id_apotek_choices(), generate_id_produk_choices(), request.POST)
            if forms.is_valid():
                try:
                    cursor.execute(
                        "insert into produk_apotek values(%s, %s, %s, %s, %s)", 
                    [
                    forms.cleaned_data['harga_jual'],
                    forms.cleaned_data['stok'],
                    forms.cleaned_data['satuan_penjualan'],
                    forms.cleaned_data['id_produk'],
                    forms.cleaned_data['id_apotek']               
                    ])
                    return redirect('produk_apotek:rud_produk_apotek') 
                except IntegrityError:
                    messages.info(request, "Error: Pasangan id apotek dan id produk tidak boleh sama dengan produk apotek yang lain")
                    return redirect('produk_apotek:create_produk_apotek')
                except DataError:
                    messages.info(request, "Error: Harga jual atau stok harus berupa angka")
                    return redirect('produk_apotek:create_produk_apotek')
        else:
            forms = produk_apotek_form(generate_id_apotek_choices(), generate_id_produk_choices())
            return render(request, 'create_produk_apotek.html', {'forms':forms})

def generate_id_apotek_choices():
    with connection.cursor() as cursor:
        cursor.execute("select id_apotek from apotek order by length(id_apotek), id_apotek")
        dict_id_apotek = dictfetchall(cursor)

        id_apotek_choices = []

        for id_apotek in dict_id_apotek:
            id_apotek_choices.append((id_apotek['id_apotek'], id_apotek['id_apotek']))
        
        return id_apotek_choices

def generate_id_produk_choices():
    with connection.cursor() as cursor:
        cursor.execute("select id_produk from produk order by length(id_produk), id_produk")
        dict_id_produk = dictfetchall(cursor)

        id_produk_choices = []

        for id_produk in dict_id_produk:
            id_produk_choices.append((id_produk['id_produk'], id_produk['id_produk']))
        
        return id_produk_choices

produk_apotek/templates/create_produk_apotek.html
{% extends 'home.html' %}

{% block content %}
<div class="container">
  <d style="text-align:center"><h1>FORM CREATE PRODUK APOTEK</h1></d>

  {% if messages %}
      <div class="alert alert-danger" role="alert">
          <h5 class="alert-heading">Gagal melakukan pembuatan Apotek</h5>
          {% for message in messages %}
              <p>{{ message }}</p>
          {% endfor %}
      </div>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      {{forms.id_apotek.label_tag}}
        <br>
        {{forms.id_apotek}}
      </div>
      <div class="form-group">
        {{forms.id_produk.label_tag}}
        <br>
        {{forms.id_produk}}
      </div>
      <div class="form-group">
        {{forms.harga_jual.label_tag}}
        <br>
        {{forms.harga_jual}}
      </div>
      <div class="form-group">
        {{forms.satuan_penjualan.label_tag}}
        <br>
        {{forms.satuan_penjualan}}
      </div>
      <div class="form-group">
        {{forms.stok.label_tag}}
        <br>
        {{forms.stok}}
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

produk_apotek/templates/produk_apotek.html
{% extends 'home.html' %}

{% block content %}
<d style="text-align:center"><h1>List Produk Apotek</h1></d>
<table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID Produk</th>
        <th scope="col">ID Apotek</th>
        <th scope="col">Harga Jual</th>
        <th scope="col">Satuan Penjualan</th>
        <th scope="col">Stok</th>
        {% if 'admin_apotek' in request.session.role %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for produk_apotek in rows %}
      <tr>
        <td>
          {{ produk_apotek.id_produk }}
        </td> 
        <td>
          {{ produk_apotek.id_apotek }}
        </td>
        <td>
          {{ produk_apotek.harga_jual }}
        </td>
        <td>
          {{ produk_apotek.satuan_penjualan }}
        </td>
        <td>
          {{ produk_apotek.stok }}
        </td>
        {% if 'admin_apotek' in request.session.role %}
        <td>
          <a href="{% url 'produk_apotek:update_produk_apotek' produk_apotek.id_apotek produk_apotek.id_produk %}">
              <button type="button" class="btn btn-success">Update</button>
          </a>
          <a href="{% url 'produk_apotek:delete_produk_apotek' produk_apotek.id_apotek produk_apotek.id_produk %}">
              <button type="button" class="btn btn-danger">Delete</button>
          </a>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

produk_apotek/templates/update_produk_apotek.html
{% extends 'home.html' %}

{% block content %}
<div class="container">
  <d style="text-align:center"><h1>FORM UPDATE PRODUK APOTEK</h1></d>

  {% if messages %}
      <div class="alert alert-danger" role="alert">
          <h5 class="alert-heading">Gagal melakukan pembuatan Apotek</h5>
          {% for message in messages %}
              <p>{{ message }}</p>
          {% endfor %}
      </div>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      {{forms.id_apotek.label_tag}}
      <br>
      {{forms.id_apotek}}
    </div>
    <div class="form-group">
      {{forms.id_produk.label_tag}}
      <br>
      {{forms.id_produk}}
    </div>
    <div class="form-group">
      {{forms.harga_jual.label_tag}}
      <br>
      {{forms.harga_jual}}
    </div>
    <div class="form-group">
      {{forms.satuan_penjualan.label_tag}}
      <br>
      {{forms.satuan_penjualan}}
    </div>
    <div class="form-group">
      {{forms.stok.label_tag}}
      <br>
      {{forms.stok}}
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
</div>
{% endblock %}