apotek/urls.py
from django.urls import path, include
from . import views

app_name = "apotek"

urlpatterns = [
    path('', views.rud_apotek, name="rud_apotek"),
    path('update/<str:id_apotek>', views.update_apotek, name='update_apotek'),
    path('delete/<str:id_apotek>', views.delete_apotek, name='delete_apotek'),
    path('create/', views.create_apotek, name='create_apotek'),
]

farmakami/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('apotek/', include('apotek.urls')),
    path('produk-apotek/', include('produk_apotek.urls')),
    path('balai-pengobatan/', include('balai_pengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/', include('transaksi_pembelian.urls')),
    path('profil/', include('profil.urls')),
    path('produk-dibeli/', include('list_produk_dibeli.urls')),
    path('pengantaran-farmasi/', include('pengantaran_farmasi.urls')),
    path('no-access/', views.no_access, name='no_access'),
]

login/urls.py
from django.urls import path, include
from . import views

app_name = "login"

urlpatterns = [
    path('', views.home_login, name="home_login"),
    path('form-login/', views.form_login, name='form_login'),
    path('form-login-submit/', views.form_login_submit, name='form_login_submit'),
    path('logout/', views.home_logout, name='home_logout'),

    path('register/', views.register, name='register'),
    path('form-register/<str:role>', views.form_register, name='form_register'),
    path('form-register-konsumen/', views.form_register_konsumen, name='form_register_konsumen'),
    path('form-register-admin/', views.form_register_admin, name='form_register_admin'),
    path('form-register-kurir/', views.form_register_kurir, name='form_register_kurir'),
    path('form-register-cs/', views.form_register_cs, name='form_register_cs'),
]

obat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.obat_read, name="obat_read"),
    path('create/', views.obat_create, name="obat_create"),
    path('create-submit/', views.obat_create_submit, name="obat_create_submit"),
    path('update/<str:id_obat>', views.obat_update, name="obat_update"),
    path('update-submit/', views.obat_update_submit, name="obat_update_submit"),
    path('delete/<str:id_obat>', views.obat_delete, name="obat_delete"),
]

produk_apotek/urls.py
from django.urls import path, include
from . import views

app_name = "produk_apotek"

urlpatterns = [
    path('', views.rud_produk_apotek, name="rud_produk_apotek"),
    path('update/<str:id_apotek>/<str:id_produk>', views.update_produk_apotek, name='update_produk_apotek'),
    path('delete/<str:id_apotek>/<str:id_produk>', views.delete_produk_apotek, name='delete_produk_apotek'),
    path('create/', views.create_produk_apotek, name='create_produk_apotek'),
]

templates/home.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>FarmaKami | {% block title %}{% endblock %}</title>
    
    <link rel="shortcut icon" href="{% static 'meta/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'meta/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'meta/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'meta/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'meta/manifest.json' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    {% block style %}{% endblock %}
</head>
<body>
    {% block navbar %}
        {% include 'navbar_auth.html' %}
    {% endblock %}
    
    {% block content %}
        
    {% endblock %}
    
    <script src="{% static 'js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/navbar_auth.html
<nav id = "navbar" class="navbar navbar-expand-lg navbar-light position-sticky fixed-top" style="background-color:#019875;">
    <a class="navbar-brand" href="{% url 'profil-home' %}">
        <div class="d-flex align-items-center">
            <h3>FarmaKami</h3>
        </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
        <li class="nav-item ml-auto">
            <a class="nav-link" href="{% url 'profil-home' %}"><b>Profil</b></a>
        </li>
        <li class="dropdown nav-item ml-auto">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login:home_login' %}"><b>Balai Pengobatan <br> & Apotek</b></a>
            <ul class="dropdown-menu">
                {% if 'admin_apotek' in request.session.role %}<li><a class="nav-link" href="{% url 'balai_pengobatan_create' %}">Buat Balai Pengobatan</a></li>{% endif %}
                <li><a class="nav-link" href="{% url 'balai_pengobatan_read' %}">Daftar Balai Pengobatan</a></li>
                {% if 'admin_apotek' in request.session.role %} <li><a class="nav-link" href="{% url 'apotek:create_apotek' %}">Buat Apotek</a></li> {% endif %}
                <li><a class="nav-link" href="{% url 'apotek:rud_apotek' %}">Daftar Apotek</a></li>
                </ul>
        </li>
        <li class="dropdown nav-item ml-auto">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login:home_login' %}"><b>Transaksi Pembelian <br> & Transaksi Resep</b></a>
            <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'tbeli-create' %}">Buat Transaksi Pembelian</a></li>
                <li><a class="nav-link" href="{% url 'tbeli-read' %}">Daftar Transaksi Pembelian</a></li>
                </ul>
        </li>
        <li class="dropdown nav-item ml-auto">
            {% if 'admin_apotek' in request.session.role %}
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login:home_login' %}"><b>Produk Apotek</b></a>
            <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'produk_apotek:create_produk_apotek' %}">Buat Produk Apotek</a></li>
                <li><a class="nav-link" href="{% url 'produk_apotek:rud_produk_apotek' %}">Daftar Produk Apotek</a></li>
                </ul>
            {% else %}
            <a class="nav-link" href="{% url 'produk_apotek:rud_produk_apotek' %}"><b>Daftar Produk Apotek</b></a>
            {% endif %}
        </li>
        <li class="dropdown nav-item ml-auto">  
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login:home_login' %}"><b>List Produk Dibeli</b></a>
            <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'pd-create' %}">Buat List Produk Dibeli</a></li>
                <li><a class="nav-link" href="{% url 'pd-rud' %}">Daftar Produk Dibeli</a></li>
                </ul>
        </li>
        <li class="dropdown nav-item ml-auto">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login:home_login' %}"><b>Pengantaran Farmasi</b></a>
            <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'pf-create' %}">Buat Pengantaran Farmasi</a></li>
                <li><a class="nav-link" href="{% url 'pf-rud' %}">Daftar Pengantaran Farmasi</a></li>
                </ul>
        </li>
        <li class="dropdown nav-item ml-auto">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'login:home_login' %}"><b>Obat</b></a>
            <ul class="dropdown-menu">
                {% if 'apoteker' in request.session.role %}<li><a class="nav-link" href="{% url 'obat_create' %}">Buat Obat</a></li>{% endif %}
                <li><a class="nav-link" href="{% url 'obat_read' %}">Daftar Obat</a></li>
                </ul>
        </li>
        <li class="nav-item ml-auto">
            <a class="nav-link" href="{% url 'login:home_logout' %}"><b>Logout</b></a>
        </li>
        </ul>
    </div>
</nav>

templates/no_access.html
{% extends 'home.html' %}

{% block content %}
<d style="text-align:center">
    <h1>Kamu tidak punya akses ke page tersebut!</h1>
</d>
{% endblock %}