farmakami/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('apotek/', include('apotek.urls')),
    path('produk-apotek/', include('produk_apotek.urls')),
    path('balai-pengobatan/', include('balai_pengobatan.urls')),
    path('obat/', include('obat.urls')),
    path('transaksipembelian/', include('transaksi_pembelian.urls')),
    path('profil/', include('profil.urls')),
    path('produk-dibeli/', include('list_produk_dibeli.urls')),
    path('pengantaran-farmasi/', include('pengantaran_farmasi.urls')),
    path('no-access/', views.no_access, name='no_access'),
]

obat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.obat_read, name="obat_read"),
    path('create/', views.obat_create, name="obat_create"),
    path('create-submit/', views.obat_create_submit, name="obat_create_submit"),
    path('update/<str:id_obat>', views.obat_update, name="obat_update"),
    path('update-submit/', views.obat_update_submit, name="obat_update_submit"),
    path('delete/<str:id_obat>', views.obat_delete, name="obat_delete"),
]

transaksi_pembelian/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.read, name='tbeli-read'),
    path('create/', views.create, name='tbeli-create'),
    path('update/<str:id_transaksi_pembelian>', views.update, name='tbeli-update'),
    path('delete/<str:id_transaksi_pembelian>', views.delete, name='tbeli-delete'),
]

transaksi_pembelian/models.py
from django.db import models

# Create your models here.

transaksi_pembelian/forms.py
from django import forms

class CreateForm(forms.Form):
    def __init__(self,id_konsumen_choices=[], *args, **kwargs, ):
        super(CreateForm, self).__init__(*args, **kwargs)
        self.fields['id_konsumen'].choices = id_konsumen_choices
    
    id_konsumen = forms.ChoiceField(label='ID Konsumen', choices=(), widget=forms.Select)

class UpdateForm(forms.Form):
    def __init__(self,id_konsumen_choices=[], *args, **kwargs, ):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.fields['id_konsumen'].choices = id_konsumen_choices

    id_transaksi = forms.CharField(label='ID Transaksi', widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'readonly' : True
    }))
    waktu_pembelian = forms.CharField(label='Waktu Pembelian', widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'readonly' : True
    }))
    total_pembayaran = forms.CharField(label='Total Pembayaran', widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'readonly' : True
    }))

    id_konsumen = forms.ChoiceField(label='ID Konsumen', choices=(), widget=forms.Select)

transaksi_pembelian/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse  
from django.db import connection, IntegrityError, ProgrammingError
from django.contrib import messages 
from login.decorators import only_pengguna
from .forms import *
from datetime import datetime

# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]   

@only_pengguna()
def read(request):
    response = {}
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM transaksi_pembelian")
        data = dictfetchall(cursor)
        for dic in data:
            dic["waktu_pembelian"] = convert_datetime(dic["waktu_pembelian"])
        response['data'] = data
    
    return render(request, "transaksi_pembelian/read.html", response)

@only_pengguna("admin_apotek")
def create(request):
    response = {}
    if request.method == "POST":
        try:
            with connection.cursor() as cursor:
                now = datetime.now()
                command = "INSERT INTO transaksi_pembelian VALUES " \
                    "('{id_transaksi}','{waktu}','{harga}','{id_konsumen}')".format(
                        id_transaksi = generate_new_id_transaksi(),
                        waktu = now,
                        harga = 0,
                        id_konsumen = request.POST['id_konsumen']
                    ) 
                cursor.execute(command)
                messages.info(request, "Sukses menambahkan transaksi pembelian")
                return redirect('tbeli-read') 
        except ProgrammingError:
            messages.info(request, "Transaksi pembelian sudah mencapai limit")
            return redirect('tbeli-create')
        except IntegrityError:
            messages.info(request, "Sudah ada id transaksi yang sama")
            return redirect('tbeli-create')
    else:
        response['form'] = CreateForm(generate_list_id_konsumen())
        return render(request, "transaksi_pembelian/create.html", response)

@only_pengguna("admin_apotek")
def update(request, id_transaksi_pembelian):
    response = {}
    if request.method == "POST":
        try:
            with connection.cursor() as cursor:
                now = datetime.now()
                command = ''' UPDATE transaksi_pembelian 
                        SET id_konsumen = '{id_konsumen}', waktu_pembelian = '{now}' 
                        WHERE id_transaksi_pembelian = '{id_transaksi}' '''.format(
                            id_konsumen = request.POST["id_konsumen"],
                            now = now,
                            id_transaksi = id_transaksi_pembelian
                        )
                cursor.execute(command)
                messages.info(request, "Sukses meng-update transaksi pembelian")
                return redirect('tbeli-read') 
        except ProgrammingError:
            messages.info(request, "Transaksi pembelian sudah mencapai limit")
            return redirect('tbeli-update')
        except IntegrityError:
            messages.info(request, "Sudah ada id transaksi yang sama")
            return redirect('tbeli-update')
    else:
        with connection.cursor() as cursor:
            command = '''SELECT * FROM transaksi_pembelian  
                        WHERE id_transaksi_pembelian = '{}' '''.format(id_transaksi_pembelian)
            cursor.execute(command)
            data = cursor.fetchall()[0]
            print(command)
            form = UpdateForm(generate_list_id_konsumen(), initial = {
                'id_transaksi' : id_transaksi_pembelian,
                'waktu_pembelian' : convert_datetime(data[1]),
                'total_pembayaran' : data[2],
            })
            response['form'] = form
        return render(request, "transaksi_pembelian/update.html", response)

@only_pengguna("admin_apotek")
def delete(request, id_transaksi_pembelian):
    with connection.cursor() as cursor:
        command = '''DELETE FROM transaksi_pembelian  
                    WHERE id_transaksi_pembelian = '{}' '''.format(id_transaksi_pembelian)
        cursor.execute(command)
        messages.info(request, "Sukses menghapus transaksi pembelian")
    return redirect("tbeli-read")

def convert_datetime(datetime):
    day = datetime.day
    month = datetime.month
    year = datetime.year
    hour = datetime.hour
    minute = datetime.minute
    second = datetime.second

    month_list = ["Januari", "Februari", "Maret", "April", "Mei", "Juni",
                    "Juli", "Agustus", "September", "Oktober", "November", "Desember"]

    result = "{0} {1} {2} {3:0>2d}:{4:0>2d}:{5:0>2d}".format(
        str(day), month_list[month-1], str(year),
        hour, minute, second)
    return result


def generate_list_id_konsumen():
    result = []
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_konsumen FROM konsumen ORDER BY LENGTH(id_konsumen), id_konsumen")
        data = cursor.fetchall()
        for row in data:
            id_konsumen = row[0]
            result.append((id_konsumen, id_konsumen))
    return result

def generate_new_id_transaksi():
    result = "beli"
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_transaksi_pembelian FROM transaksi_pembelian ORDER BY LENGTH(id_transaksi_pembelian), id_transaksi_pembelian DESC LIMIT 1")
        data = cursor.fetchall()[0]
        latest_id_transaksi = data[0]
        result += str(int(latest_id_transaksi[4:]) + 1)
    return result            

transaksi_pembelian/templates/transaksi_pembelian/create.html
{% extends 'home.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center display-4">Buat Transaksi Pembelian</h1>
        {% if messages %}
            <div class="alert alert-danger" role="alert">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <br>
            <div class="col text-center">
                <button type="submit" class="btn btn-info text-center">Submit</button>
            </div>
        </form>
    </div>

{% endblock %}

transaksi_pembelian/templates/transaksi_pembelian/read.html
{% extends 'home.html' %}

{% block content %}
    <div>
        <h1 class="text-center display-4">Daftar Transaksi Pembelian</h1>
        {% if messages %}
            <div class="alert alert-success">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="table-responsive">
            <table class="table table-bordered text-center">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">ID Transaksi</th>
                    <th scope="col">Waktu Pembelian</th>
                    <th scope="col">Total Pembelian</th>
                    {% if 'konsumen' not in request.session.role or request.session.role|length > 1 %}
                        <th scope="col">ID Konsumen</th>
                    {% endif %}
                    {% if 'admin_apotek' in request.session.role %}
                        <th scope="col">Action</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for row in data %}
                <tr>
                    <td class="align-middle">{{ row.id_transaksi_pembelian }}</td>
                    <td class="align-middle">{{ row.waktu_pembelian }}</td>
                    <td class="align-middle">{{ row.total_pembayaran }}</td>
                    {% if 'konsumen' not in request.session.role or request.session.role|length > 1 %}
                        <td class="align-middle">{{ row.id_konsumen }}</td>
                    {% endif %}
                    {% if 'admin_apotek' in request.session.role %}
                        <td class="align-middle">
                            <a href="{% url 'tbeli-update' row.id_transaksi_pembelian %}"><button type="button" class="btn btn-info btn-sm">Update</button></a>
                            <a href="{% url 'tbeli-delete' row.id_transaksi_pembelian %}"><button type="button" class="btn btn-danger btn-sm">Delete</button></a>
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

transaksi_pembelian/templates/transaksi_pembelian/update.html
{% extends 'home.html' %}

{% block style %}
<style>
    #id_id_konsumen {
        margin-top: 1rem;
    }
</style>
{% endblock %}

{% block content %}
    <div  class="container">
        <h1 class="text-center display-4">Update Transaksi Pembelian</h1>
        {% if messages %}
            <div class="alert alert-danger" role="alert">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <br>
            <div class="col text-center"><button type="submit" class="btn btn-info text-center">Submit</button>
        </form>
    </div>

{% endblock %}